
#special_compile_flags = -D BSV_TIMESCALE=1ns/1ps -sched-dot
special_compile_flags = -sched-dot

#MAINV= ${BLUESPECDIR}/Verilog/main.v
MAINV=${PWD}/../main.v

sim_top= Tb.bsv

include ${BSV}/bsv.mk


